name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Déclenchement sur la branche principale

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Vérification du code
    - name: Checkout code
      uses: actions/checkout@v3

    # Connexion au Docker Registry
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construction et taggage de l'image Docker
    - name: Build Docker Image with Commit SHA Tag
      env:
        COMMIT_SHA: ${{ github.sha }}
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-python-app:${COMMIT_SHA} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/my-python-app:${COMMIT_SHA} ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest

    # Push des tags dans le Docker Registry
    - name: Push Docker Images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    # Connexion SSH au cluster Docker Swarm
    - name: Deploy to Docker Swarm
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker service update --image ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }} my-python-service
